<%@ Page Title="Manage Roles" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ManageRoles.aspx.cs" Inherits="TLGX_Consumer.Account.ManageRoles" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <div class="form-horizontal">
        <h4>Assign / Manage User Roles</h4>
        <hr />
        <br />
        <div id="dvCreateRole" runat="server" class="form-horizontal">
            <h5>Create New Role</h5>
            <hr />
            <div class="form-group">
                <asp:Label runat="server" AssociatedControlID="txtRole" CssClass="col-md-2 control-label">Enter Role Name:</asp:Label>
                <div class="col-md-10">
                    <asp:TextBox runat="server" ID="txtRole" CssClass="form-control" />
                    <asp:RequiredFieldValidator runat="server" ControlToValidate="txtRole"
                        CssClass="text-danger" ErrorMessage="The Role field is required." />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <asp:Button ID="btnCreate" runat="server" OnClick="btnCreate_Click" Text="Create Role" CssClass="btn btn-default" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <asp:Label ID="lblResult" runat="server" Font-Bold="true" />
                </div>
            </div>
        </div>
        <div id="dvAssignRole" runat="server" class="form-horizontal">
            <h5>Assign Role to User</h5>
            <hr />
            <div>
                <div class="form-group">
                    <div class="col-md-10">
                        <asp:DropDownList ID="ddlUsers" runat="server" OnSelectedIndexChanged="ddlUsers_SelectedIndexChanged" AutoPostBack="true"></asp:DropDownList>
                        <asp:RequiredFieldValidator runat="server" ControlToValidate="ddlUsers"
                            CssClass="text-danger" ErrorMessage="Select User" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <asp:GridView ID="gvRoles" runat="server" CssClass="Gridview" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="gvRoles_RowDeleting"
                            OnRowDataBound="gvRoles_RowDataBound">
                            <HeaderStyle BackColor="#df5015" />
                            <Columns>
                                <asp:TemplateField HeaderText="Role Name">
                                    <ItemTemplate>
                                        <asp:Label ID="lblRole" runat="server" Text='<%# Bind("Name") %>' />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="">
                                    <ItemTemplate>
                                        <asp:CheckBox ID="chkAddRole" runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <asp:Button ID="btnAssignRole" runat="server" OnClick="btnAssignRole_Click" Text="Assign Role" CssClass="btn btn-default" CausesValidation="false" />
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div id="dvDisplayRoles" runat="server" class="form-horizontal">
            <table align="left">
                <tr>
                    <td><b>Roles Assigned to Users:</b></td>
                    <td>
                        <asp:Label ID="lblUserRoleCount" runat="server" Font-Bold="true" /></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <asp:GridView ID="gvUserRoles" runat="server" CssClass="Gridview" AutoGenerateColumns="false">
                            <HeaderStyle BackColor="#df5015" />
                            <Columns>
                                <asp:TemplateField HeaderText="Role Name">
                                    <ItemTemplate>
                                        <asp:Label ID="lblRole" runat="server" Text='<%# Bind("Name") %>' />
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                        </asp:GridView>
                    </td>
                </tr>
            </table>
        </div>
    </div>

</asp:Content>
