//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLGX_Consumer.activity {
    
    
    public partial class ManageActivityFlavour {
        
        /// <summary>
        /// Flavours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.activity.ManageActivityFlavours.Flavours Flavours;
        
        /// <summary>
        /// ActivityDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.activity.ManageActivityFlavours.ActivityDescription ActivityDescription;
        
        /// <summary>
        /// Inclusions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.activity.ManageActivityFlavours.InclusionsAndExclusion Inclusions;
        
        /// <summary>
        /// ClassificationAttributes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.activity.ManageActivityFlavours.ClassificationAttributes ClassificationAttributes;
        
        /// <summary>
        /// ActivityMedia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.activity.ManageActivityFlavours.ActivityMedia ActivityMedia;
        
        /// <summary>
        /// Policy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.activity.ManageActivityFlavours.Policy Policy;
        
        /// <summary>
        /// PricesNDeals control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.activity.ManageActivityFlavours.PricesNDeals PricesNDeals;
        
        /// <summary>
        /// ReviewsNScores control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.activity.ManageActivityFlavours.ReviewsNScores ReviewsNScores;
        
        /// <summary>
        /// SupplierProductMappings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.activity.ManageActivityFlavours.SupplierProductMappings SupplierProductMappings;
        
        /// <summary>
        /// FlavourOptions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.activity.ManageActivityFlavours.FlavourOptions FlavourOptions;
        
        /// <summary>
        /// PreviousPage property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new TLGX_Consumer.activity.search PreviousPage {
            get {
                return ((TLGX_Consumer.activity.search)(base.PreviousPage));
            }
        }
    }
}
