//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLGX_Consumer.admin {
    
    
    public partial class manageWorkflowMaster {
        
        /// <summary>
        /// ApprovalRoleMaster control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.masters.ApprovalRoleMaster ApprovalRoleMaster;
        
        /// <summary>
        /// ApprovalStatusMaster control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.masters.ApprovalStatusMaster ApprovalStatusMaster;
        
        /// <summary>
        /// ActivityMaster control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.masters.ActivityMaster ActivityMaster;
        
        /// <summary>
        /// workflowmessagecomposer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TLGX_Consumer.controls.workflow.workflowmessagecomposer workflowmessagecomposer;
    }
}
