//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLGX_Consumer.staticdata {
    
    
    public partial class searchAccommodationProductMapping {
        
        /// <summary>
        /// searchAccoMapping control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        public global::TLGX_Consumer.controls.staticdata.AccoMap searchAccoMapping;
    }
}
