//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLGX_Consumer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public System.Guid Address_Id { get; set; }
        public Nullable<System.Guid> Accommodation_Id { get; set; }
        public string AddressType { get; set; }
        public string BranchName { get; set; }
        public string StreetName { get; set; }
        public string StreetNumber { get; set; }
        public string Street3 { get; set; }
        public string Street4 { get; set; }
        public string Street5 { get; set; }
        public string PostalCode { get; set; }
        public string Town { get; set; }
        public string Location { get; set; }
        public string Area { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Country { get; set; }
        public string SuburbDowntown { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longtitude { get; set; }
        public string LEGACY_COUNTRY { get; set; }
        public string LEGACY_CITY { get; set; }
        public string Country_ISO { get; set; }
        public string City_ISO { get; set; }
        public string STATE_NAME { get; set; }
        public string STATE_ISO { get; set; }
        public string LEGACY_STATE { get; set; }
        public Nullable<int> CompanyName { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Edit_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
    }
}
