//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLGX_Consumer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stg_ezhtlfs_hotel_format
    {
        public string srno { get; set; }
        public string hotel_id { get; set; }
        public string supplier_name { get; set; }
        public string Star { get; set; }
        public string hotel_name { get; set; }
        public string address1 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string Pin { get; set; }
        public string Location { get; set; }
        public string credit_cards { get; set; }
        public string area { get; set; }
        public string hotel_facilities { get; set; }
        public string room_facilities { get; set; }
        public string resturants_desc { get; set; }
        public string meeting_facilities { get; set; }
        public string hoteldescription { get; set; }
        public string checkin { get; set; }
        public string checkout { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string no_of_rooms { get; set; }
        public string dist_fm_airport { get; set; }
        public string distance_frm_station { get; set; }
        public string distance_frm_bus { get; set; }
        public string dist_fm_cityctr { get; set; }
        public Nullable<bool> Restaurant_yn { get; set; }
        public Nullable<bool> conference_yn { get; set; }
        public Nullable<bool> fitness_yn { get; set; }
        public Nullable<bool> travel_yn { get; set; }
        public Nullable<bool> forex_yn { get; set; }
        public Nullable<bool> shopping_yn { get; set; }
        public Nullable<bool> banquet_yn { get; set; }
        public Nullable<bool> games_yn { get; set; }
        public Nullable<bool> Bar_yn { get; set; }
        public Nullable<bool> Coffee_Shop_yn { get; set; }
        public Nullable<bool> Room_Service_yn { get; set; }
        public Nullable<bool> Internet_Access_yn { get; set; }
        public Nullable<bool> Business_Centre_yn { get; set; }
        public Nullable<bool> Swimming_Pool_yn { get; set; }
        public Nullable<bool> Pets_yn { get; set; }
        public Nullable<bool> Tennis_Court_yn { get; set; }
        public Nullable<bool> Golf_yn { get; set; }
        public Nullable<bool> Air_Conditioning_yn { get; set; }
        public Nullable<bool> Parking_yn { get; set; }
        public Nullable<bool> Wheel_Chair_yn { get; set; }
        public Nullable<bool> Health_Club_yn { get; set; }
        public string hotel_chain { get; set; }
        public string recommends { get; set; }
        public string notes { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public string ped_by { get; set; }
        public Nullable<System.DateTime> ped_on { get; set; }
        public string pup_by { get; set; }
        public Nullable<System.DateTime> pup_on { get; set; }
        public string htl_block { get; set; }
        public string htl_block_by { get; set; }
        public string htl_latitude { get; set; }
        public string htl_longitude { get; set; }
        public string brand_name { get; set; }
        public string theme { get; set; }
        public string geo_area { get; set; }
        public string block_reason { get; set; }
        public string suburbs { get; set; }
        public Nullable<bool> url_sub { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public int htl_id { get; set; }
    }
}
